#!/usr/bin/env python3
"""Hindsight — a machine that guesses tomorrow, in public, and keeps score.

Each run does three things, in this order:

  1. OBSERVE — fetch today's readings (the truth that settles yesterday's bets).
  2. PREDICT — call tomorrow, from a stated rule, with a stated confidence.
  3. GRADE   — re-derive every past prediction's outcome from the archive.

The predictions are committed and pushed *before* the outcome exists, so the git
history is the proof they were not backdated. That is the whole point: anyone
can check the timestamps against the archive.

Six keyless sources, standard library only, every fetch wrapped in try/except.
If a source is down we simply make no call from it that day, and the daily
commit still happens.

Grading is a *pure function of the archive* — it is recomputed from scratch on
every run rather than accumulated. A bad day can never corrupt the ledger, and
`ledger.json` can always be regenerated by re-running the script.
"""

from __future__ import annotations

import json
import os
import time
import urllib.request
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).parent
ARCHIVE = ROOT / "archive"
README = ROOT / "README.md"

# The city whose forecast we grade. Override with env vars to move it.
CITY_NAME = os.environ.get("CITY_NAME", "New Delhi")
CITY_LAT = os.environ.get("CITY_LAT", "28.6139")
CITY_LON = os.environ.get("CITY_LON", "77.2090")
CITY_TZ = os.environ.get("CITY_TZ", "Asia/Kolkata")

# How close the forecaster has to land to count as a hit.
FORECAST_TOLERANCE_C = 2.0

HEADERS = {"User-Agent": "hindsight-prediction-ledger/1.0 (+github actions)"}


# --------------------------------------------------------------------------
# fetching
# --------------------------------------------------------------------------


def _get(url: str, timeout: int = 20, retries: int = 3) -> bytes:
    last_err = None
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url, headers=HEADERS)
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                return resp.read()
        except Exception as err:
            last_err = err
            if attempt < retries - 1:
                time.sleep(2**attempt)  # 1s, 2s backoff
    raise last_err


def _get_json(url: str):
    return json.loads(_get(url))


# --------------------------------------------------------------------------
# observers — each returns a plain dict, or raises
# --------------------------------------------------------------------------


def observe_btc() -> dict:
    url = (
        "https://api.coingecko.com/api/v3/simple/price"
        "?ids=bitcoin&vs_currencies=usd&include_24hr_change=true"
    )
    data = _get_json(url)["bitcoin"]
    return {
        "usd": data.get("usd"),
        "usd_24h_change": round(data.get("usd_24h_change", 0.0), 2),
    }


def observe_kp() -> dict:
    """Planetary K-index — geomagnetic activity, 3-hourly, from NOAA SWPC."""
    rows = _get_json("https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json")
    # NOAA serves this as a list of objects, but has historically served an
    # array-of-arrays with a header row. Accept either; skip anything odd.
    values = []
    for row in rows:
        try:
            value = row.get("Kp", row.get("kp_index")) if isinstance(row, dict) else row[1]
            values.append(float(value))
        except (ValueError, TypeError, KeyError, IndexError):
            continue
    if not values:
        raise RuntimeError("no Kp values parsed")
    last24 = values[-8:]  # 8 readings x 3 hours
    return {"max_kp": max(last24), "latest_kp": last24[-1], "samples": len(last24)}


def observe_quakes() -> dict:
    url = "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson"
    features = _get_json(url).get("features", [])
    mags = [
        f["properties"]["mag"]
        for f in features
        if isinstance(f.get("properties", {}).get("mag"), (int, float))
    ]
    if not mags:
        raise RuntimeError("no magnitudes in feed")
    strongest = max(features, key=lambda f: f["properties"].get("mag") or -99)
    return {
        "max_mag": round(max(mags), 2),
        "count": len(mags),
        "strongest_place": strongest["properties"].get("place"),
    }


def observe_wiki() -> dict:
    """The most-read English Wikipedia article for the last *complete* day."""
    day = datetime.now(timezone.utc) - timedelta(days=1)
    url = (
        "https://wikimedia.org/api/rest_v1/metrics/pageviews/top/"
        f"en.wikipedia/all-access/{day:%Y/%m/%d}"
    )
    articles = _get_json(url)["items"][0]["articles"]
    skip = {"Main_Page", "Special:Search", "-"}
    for art in articles:
        name = art.get("article", "")
        if name in skip or name.startswith("Special:"):
            continue
        return {
            "top": name,
            "views": art.get("views"),
            "for_date": f"{day:%Y-%m-%d}",
        }
    raise RuntimeError("no eligible article")


def observe_hn() -> dict:
    ids = _get_json("https://hacker-news.firebaseio.com/v0/topstories.json")[:10]
    if not ids:
        raise RuntimeError("empty top stories")
    title = None
    try:
        item = _get_json(f"https://hacker-news.firebaseio.com/v0/item/{ids[0]}.json")
        title = (item or {}).get("title")
    except Exception:
        pass  # the title is decoration; the id is what we actually grade on
    return {"top_id": ids[0], "top_title": title, "top10": ids}


def observe_weather() -> dict:
    """Daily highs for yesterday (settled) and tomorrow (forecast).

    `actual_prev` is a completed observation, which is what lets us grade a
    forecast honestly two days after it was made.
    """
    url = (
        "https://api.open-meteo.com/v1/forecast"
        f"?latitude={CITY_LAT}&longitude={CITY_LON}"
        "&daily=temperature_2m_max"
        f"&timezone={CITY_TZ.replace('/', '%2F')}"
        "&past_days=1&forecast_days=2"
    )
    daily = _get_json(url)["daily"]
    days, highs = daily["time"], daily["temperature_2m_max"]
    if len(days) < 3 or len(highs) < 3:
        raise RuntimeError("unexpected forecast shape")
    return {
        "city": CITY_NAME,
        "actual_prev": highs[0],
        "actual_prev_date": days[0],
        "today": highs[1],
        "forecast_next": highs[2],
        "forecast_next_date": days[2],
    }


OBSERVERS = {
    "btc": observe_btc,
    "kp": observe_kp,
    "quakes": observe_quakes,
    "wiki": observe_wiki,
    "hn": observe_hn,
    "weather": observe_weather,
}


# --------------------------------------------------------------------------
# archive access helpers
# --------------------------------------------------------------------------


def obs_of(days: dict, date: str, key: str):
    """Return day `date`'s observation `key`, or None if absent/failed."""
    day = days.get(date)
    if not isinstance(day, dict):
        return None
    value = (day.get("observations") or {}).get(key)
    if not isinstance(value, dict) or "error" in value:
        return None
    return value


def shift(date: str, delta: int) -> str:
    return (datetime.strptime(date, "%Y-%m-%d") + timedelta(days=delta)).strftime(
        "%Y-%m-%d"
    )


def _rate(days: dict, test, default: float, minimum: int = 5) -> float:
    """Historical frequency of `test` across archived days, for honest priors."""
    hits = [test(d) for d in days.values()]
    hits = [h for h in hits if h is not None]
    if len(hits) < minimum:
        return default
    return sum(hits) / len(hits)


# --------------------------------------------------------------------------
# predictors — make() calls tomorrow, resolve() reads the truth back out
# --------------------------------------------------------------------------
#
# make(obs, days, today) -> (call: bool, confidence: float, basis: dict) | None
#   confidence is always >= 0.5: it is confidence *in the call made*, not in
#   the event happening. A 0.7 "no" means 70% sure it will not happen.
#
# resolve(pred, days) -> bool | None
#   the actual outcome, or None if it cannot be settled yet (still open) or
#   the data needed to settle it never arrived (void).


def make_btc(obs, days, today):
    btc = obs.get("btc")
    if not btc or btc.get("usd") is None:
        return None
    change = btc.get("usd_24h_change") or 0.0
    up = change >= 0
    # Momentum, held to a modest confidence — this is close to a coin flip and
    # pretending otherwise is how you get a bad calibration curve.
    conf = min(0.60, 0.52 + abs(change) / 100.0)
    return up, round(conf, 3), {"today_usd": btc["usd"], "change_24h": change}


def resolve_btc(pred, days):
    before = obs_of(days, pred["made_on"], "btc")
    after = obs_of(days, pred["resolve_on"], "btc")
    if not before or not after:
        return None
    if before.get("usd") is None or after.get("usd") is None:
        return None
    return after["usd"] > before["usd"]


def make_kp(obs, days, today):
    kp = obs.get("kp")
    if not kp or kp.get("max_kp") is None:
        return None
    active = kp["max_kp"] > 3
    # Persistence: geomagnetic activity clusters, so today's state is the best
    # cheap guess at tomorrow's.
    return active, 0.70 if active else 0.78, {"today_max_kp": kp["max_kp"]}


def resolve_kp(pred, days):
    after = obs_of(days, pred["resolve_on"], "kp")
    if not after or after.get("max_kp") is None:
        return None
    return after["max_kp"] > 3


def make_quake(obs, days, today):
    if not obs.get("quakes"):
        return None
    rate = _rate(
        days,
        lambda d: (
            (d.get("observations") or {}).get("quakes", {}).get("max_mag", 0) >= 5.0
            if isinstance((d.get("observations") or {}).get("quakes"), dict)
            else None
        ),
        default=0.85,
    )
    call = rate >= 0.5
    conf = rate if call else 1 - rate
    return call, round(min(0.95, max(0.5, conf)), 3), {"base_rate": round(rate, 3)}


def resolve_quake(pred, days):
    after = obs_of(days, pred["resolve_on"], "quakes")
    if not after or after.get("max_mag") is None:
        return None
    return after["max_mag"] >= 5.0


def make_wiki(obs, days, today):
    wiki = obs.get("wiki")
    if not wiki or not wiki.get("top"):
        return None
    prev = obs_of(days, shift(today, -1), "wiki")
    streaking = bool(prev and prev.get("top") == wiki["top"])
    # An article that has already held the top spot two days running tends to
    # hold it again; a one-day spike usually does not.
    call = streaking
    return call, 0.70 if streaking else 0.62, {"today_top": wiki["top"]}


def resolve_wiki(pred, days):
    before = obs_of(days, pred["made_on"], "wiki")
    after = obs_of(days, pred["resolve_on"], "wiki")
    if not before or not after or not before.get("top") or not after.get("top"):
        return None
    return after["top"] == before["top"]


def make_hn(obs, days, today):
    hn = obs.get("hn")
    if not hn or hn.get("top_id") is None:
        return None
    # The front page churns hard; falling out of the top 10 within a day is the
    # overwhelming default.
    return True, 0.88, {"top_id": hn["top_id"], "top_title": hn.get("top_title")}


def resolve_hn(pred, days):
    after = obs_of(days, pred["resolve_on"], "hn")
    if not after or not after.get("top10"):
        return None
    return pred["basis"]["top_id"] not in after["top10"]


def make_forecast(obs, days, today):
    weather = obs.get("weather")
    if not weather or weather.get("forecast_next") is None:
        return None
    # We are not predicting the weather. We are predicting whether the weather
    # service gets it right — and quietly building a scorecard on them.
    return (
        True,
        0.80,
        {
            "forecast_c": weather["forecast_next"],
            "for_date": weather.get("forecast_next_date"),
            "city": weather.get("city"),
        },
    )


def resolve_forecast(pred, days):
    """Settled by whichever later run carried the completed high for that date."""
    target = pred["basis"].get("for_date") or pred["resolve_on"]
    forecast = pred["basis"].get("forecast_c")
    if forecast is None:
        return None
    for date in sorted(days):
        if date <= pred["made_on"]:
            continue
        weather = obs_of(days, date, "weather")
        if not weather:
            continue
        if weather.get("actual_prev_date") == target and weather.get("actual_prev") is not None:
            return abs(weather["actual_prev"] - forecast) <= FORECAST_TOLERANCE_C
    return None


PREDICTORS = {
    "btc_up": {
        "question": "Bitcoin will be higher tomorrow than it is today.",
        "rule": "momentum",
        "horizon": 1,
        "make": make_btc,
        "resolve": resolve_btc,
    },
    "kp_storm": {
        "question": "Geomagnetic Kp will exceed 3 within the next 24 hours.",
        "rule": "persistence",
        "horizon": 1,
        "make": make_kp,
        "resolve": resolve_kp,
    },
    "quake_m5": {
        "question": "A magnitude 5.0+ earthquake will strike somewhere tomorrow.",
        "rule": "base rate",
        "horizon": 1,
        "make": make_quake,
        "resolve": resolve_quake,
    },
    "wiki_hold": {
        "question": "Today's most-read Wikipedia article will still be #1 tomorrow.",
        "rule": "persistence",
        "horizon": 1,
        "make": make_wiki,
        "resolve": resolve_wiki,
    },
    "hn_fade": {
        "question": "The current #1 story on Hacker News will fall out of the top 10.",
        "rule": "decay",
        "horizon": 1,
        "make": make_hn,
        "resolve": resolve_hn,
    },
    "forecast_hit": {
        "question": (
            f"Tomorrow's high in {CITY_NAME} will land within "
            f"{FORECAST_TOLERANCE_C:g}°C of today's forecast."
        ),
        "rule": "trust the forecaster",
        "horizon": 2,  # needs a *completed* day, so it settles a day later
        "make": make_forecast,
        "resolve": resolve_forecast,
    },
}


# --------------------------------------------------------------------------
# the three phases
# --------------------------------------------------------------------------


def collect_observations() -> dict:
    out = {}
    for name, fn in OBSERVERS.items():
        try:
            out[name] = fn()
            print(f"[ok]   observe {name}")
        except Exception as err:
            out[name] = {"error": str(err)}
            print(f"[fail] observe {name}: {err}")
    return out


def make_predictions(obs: dict, days: dict, today: str) -> list:
    preds = []
    for pid, spec in PREDICTORS.items():
        try:
            result = spec["make"](obs, days, today)
        except Exception as err:
            print(f"[fail] predict {pid}: {err}")
            continue
        if result is None:
            print(f"[skip] predict {pid}: no data")
            continue
        call, confidence, basis = result
        preds.append(
            {
                "id": pid,
                "question": spec["question"],
                "rule": spec["rule"],
                "call": bool(call),
                "confidence": float(confidence),
                "basis": basis,
                "made_on": today,
                "resolve_on": shift(today, spec["horizon"]),
            }
        )
        print(f"[ok]   predict {pid}: {call} @ {confidence}")
    return preds


def grade_all(days: dict) -> list:
    """Re-derive every settled prediction from the archive. Pure and idempotent.

    Anything that cannot be settled is simply absent — still open, or void
    because the day that would have settled it never got archived.
    """
    grades = []
    for date in sorted(days):
        for pred in days[date].get("predictions") or []:
            spec = PREDICTORS.get(pred.get("id"))
            if not spec:
                continue
            try:
                actual = spec["resolve"](pred, days)
            except Exception:
                actual = None
            if actual is None:
                continue
            grades.append(
                {
                    "id": pred["id"],
                    "question": pred.get("question"),
                    "rule": pred.get("rule"),
                    "made_on": pred["made_on"],
                    "resolve_on": pred["resolve_on"],
                    "call": pred["call"],
                    "confidence": pred["confidence"],
                    "actual": actual,
                    "correct": pred["call"] == actual,
                }
            )
    return grades


# --------------------------------------------------------------------------
# the ledger
# --------------------------------------------------------------------------

BUCKETS = ((0.5, 0.6), (0.6, 0.7), (0.7, 0.8), (0.8, 0.9), (0.9, 1.001))


def build_ledger(days: dict, grades: list, today: str) -> dict:
    graded = len(grades)
    correct = sum(1 for g in grades if g["correct"])

    # Brier score: mean squared error of the probability assigned to the event
    # actually happening. 0 is perfect, 0.25 is what you get by always saying
    # "50%", and anything above that is worse than useless.
    brier = None
    if graded:
        total = 0.0
        for g in grades:
            p_event = g["confidence"] if g["call"] else 1 - g["confidence"]
            total += (p_event - (1.0 if g["actual"] else 0.0)) ** 2
        brier = round(total / graded, 4)

    by_predictor = {}
    for pid, spec in PREDICTORS.items():
        mine = [g for g in grades if g["id"] == pid]
        hits = sum(1 for g in mine if g["correct"])
        by_predictor[pid] = {
            "question": spec["question"],
            "rule": spec["rule"],
            "graded": len(mine),
            "correct": hits,
            "accuracy": round(hits / len(mine), 4) if mine else None,
        }

    calibration = []
    for low, high in BUCKETS:
        mine = [g for g in grades if low <= g["confidence"] < high]
        if not mine:
            calibration.append(
                {"label": f"{int(low*100)}–{int(high*100)}%", "n": 0,
                 "claimed": None, "actual": None}
            )
            continue
        calibration.append(
            {
                "label": f"{int(low*100)}–{int(high*100)}%",
                "n": len(mine),
                "claimed": round(sum(g["confidence"] for g in mine) / len(mine), 4),
                "actual": round(sum(1 for g in mine if g["correct"]) / len(mine), 4),
            }
        )

    settled = {(g["made_on"], g["id"]) for g in grades}
    open_bets, void = [], 0
    for date in sorted(days):
        for pred in days[date].get("predictions") or []:
            if (pred["made_on"], pred["id"]) in settled:
                continue
            if pred["resolve_on"] > today:
                open_bets.append(pred)
            else:
                void += 1

    return {
        "updated": datetime.now(timezone.utc).isoformat(),
        "totals": {
            "graded": graded,
            "correct": correct,
            "accuracy": round(correct / graded, 4) if graded else None,
            "brier": brier,
            "open": len(open_bets),
            "void": void,
            "days": len(days),
        },
        "by_predictor": by_predictor,
        "calibration": calibration,
        "open_bets": open_bets,
        "grades": grades,
    }


def build_index(days: dict, grades: list) -> list:
    """One entry per archived day, for the hit/miss calendar."""
    entries = []
    for date in sorted(days):
        day = days[date]
        captured = [
            name
            for name in OBSERVERS
            if isinstance((day.get("observations") or {}).get(name), dict)
            and "error" not in day["observations"][name]
        ]
        mine = [g for g in grades if g["made_on"] == date]
        entries.append(
            {
                "date": date,
                "captured": captured,
                "made": len(day.get("predictions") or []),
                "graded": len(mine),
                "correct": sum(1 for g in mine if g["correct"]),
            }
        )
    return entries


# --------------------------------------------------------------------------
# writing
# --------------------------------------------------------------------------


def load_days() -> dict:
    days = {}
    if not ARCHIVE.exists():
        return days
    for path in sorted(ARCHIVE.glob("*.json")):
        if path.stem in ("latest", "index", "ledger"):
            continue
        try:
            day = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            continue
        if isinstance(day, dict) and day.get("date"):
            days[day["date"]] = day
    return days


def _write(path: Path, payload) -> None:
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    try:
        shown = path.relative_to(ROOT)
    except ValueError:  # writing outside the repo (tests, backfills)
        shown = path
    print(f"wrote {shown}")


def update_readme(snapshot: dict, ledger: dict) -> None:
    if not README.exists():
        return
    totals = ledger["totals"]
    lines = [
        "<!-- LEDGER:START -->",
        f"### 🎲 Standing — {snapshot['date']}",
        "",
    ]
    if totals["graded"]:
        lines += [
            f"**{totals['correct']} right / {totals['graded']} settled "
            f"({totals['accuracy']:.0%})** · Brier {totals['brier']:.3f} "
            f"· {totals['open']} still open",
            "",
            "| Call | Rule | Record |",
            "| --- | --- | --- |",
        ]
        for pid, row in ledger["by_predictor"].items():
            record = (
                f"{row['correct']}/{row['graded']} ({row['accuracy']:.0%})"
                if row["graded"]
                else "—"
            )
            lines.append(f"| {row['question']} | {row['rule']} | {record} |")
        lines.append("")
    else:
        lines += ["_No bets have settled yet — the first ones resolve tomorrow._", ""]

    if snapshot.get("predictions"):
        lines += ["**Open bets, placed today:**", ""]
        for pred in snapshot["predictions"]:
            verdict = "**yes**" if pred["call"] else "**no**"
            lines.append(
                f"- {verdict} — {pred['question']} "
                f"_({pred['confidence']:.0%} confident, {pred['rule']})_"
            )
        lines.append("")
    lines.append("<!-- LEDGER:END -->")
    block = "\n".join(lines)

    text = README.read_text(encoding="utf-8")
    start, end = "<!-- LEDGER:START -->", "<!-- LEDGER:END -->"
    if start in text and end in text:
        text = text[: text.index(start)] + block + text[text.index(end) + len(end) :]
    else:
        text = text.rstrip() + "\n\n" + block + "\n"
    README.write_text(text, encoding="utf-8")
    print("wrote README.md")


def main() -> None:
    now = datetime.now(timezone.utc)
    today = now.strftime("%Y-%m-%d")
    ARCHIVE.mkdir(exist_ok=True)

    days = load_days()

    print("-- observe --")
    observations = collect_observations()

    print("-- predict --")
    predictions = make_predictions(observations, days, today)

    snapshot = {
        "date": today,
        "fetched_at": now.isoformat(),
        "observations": observations,
        "predictions": predictions,
    }
    _write(ARCHIVE / f"{today}.json", snapshot)
    days[today] = snapshot

    print("-- grade --")
    grades = grade_all(days)
    ledger = build_ledger(days, grades, today)
    totals = ledger["totals"]
    print(
        f"settled {totals['graded']} · correct {totals['correct']} "
        f"· open {totals['open']} · void {totals['void']}"
    )

    _write(ARCHIVE / "latest.json", snapshot)
    _write(ARCHIVE / "ledger.json", ledger)
    _write(ARCHIVE / "index.json", build_index(days, grades))
    update_readme(snapshot, ledger)
    print("done")


if __name__ == "__main__":
    main()
