#!/usr/bin/env python3
"""Hindsight — a machine that guesses tomorrow, in public, and keeps score.

Each run does three things, in this order:

  1. OBSERVE — fetch today's readings (the truth that settles yesterday's bets).
  2. PREDICT — call tomorrow, from a stated rule, with a stated confidence.
  3. GRADE   — re-derive every past prediction's outcome from the archive.

The predictions are committed and pushed *before* the outcome exists, so the git
history is the proof they were not backdated. That is the whole point: anyone
can check the timestamps against the archive.

Six keyless sources, standard library only, every fetch wrapped in try/except.
If a source is down we simply make no call from it that day, and the daily
commit still happens.

Grading is a *pure function of the archive* — it is recomputed from scratch on
every run rather than accumulated. A bad day can never corrupt the ledger, and
`ledger.json` can always be regenerated by re-running the script.
"""

from __future__ import annotations

import json
import math
import os
import time
import urllib.request
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).parent
ARCHIVE = ROOT / "archive"
README = ROOT / "README.md"

def env(name: str, default: str) -> str:
    """Like os.environ.get, but treats an empty value as absent.

    GitHub Actions substitutes an unset repo variable as "" rather than leaving
    it out, so a plain .get() would hand us a blank latitude and build a URL
    that quietly 400s. Anything blank falls back to the default.
    """
    return os.environ.get(name, "").strip() or default


# The city whose forecast we grade. Override with env vars to move it.
CITY_NAME = env("CITY_NAME", "New Delhi")
CITY_LAT = env("CITY_LAT", "28.6139")
CITY_LON = env("CITY_LON", "77.2090")
CITY_TZ = env("CITY_TZ", "Asia/Kolkata")

# How close the forecaster has to land to count as a hit.
FORECAST_TOLERANCE_C = 2.0

HEADERS = {"User-Agent": "hindsight-prediction-ledger/1.0 (+github actions)"}


# --------------------------------------------------------------------------
# fetching
# --------------------------------------------------------------------------


def _get(url: str, timeout: int = 20, retries: int = 3) -> bytes:
    last_err = None
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url, headers=HEADERS)
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                return resp.read()
        except Exception as err:
            last_err = err
            if attempt < retries - 1:
                time.sleep(2**attempt)  # 1s, 2s backoff
    raise last_err


def _get_json(url: str):
    return json.loads(_get(url))


# --------------------------------------------------------------------------
# observers — each returns a plain dict, or raises
# --------------------------------------------------------------------------


def observe_btc() -> dict:
    url = (
        "https://api.coingecko.com/api/v3/simple/price"
        "?ids=bitcoin&vs_currencies=usd&include_24hr_change=true"
    )
    data = _get_json(url)["bitcoin"]
    return {
        "usd": data.get("usd"),
        "usd_24h_change": round(data.get("usd_24h_change", 0.0), 2),
    }


def observe_kp() -> dict:
    """Planetary K-index — geomagnetic activity, 3-hourly, from NOAA SWPC."""
    rows = _get_json("https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json")
    # NOAA serves this as a list of objects, but has historically served an
    # array-of-arrays with a header row. Accept either; skip anything odd.
    values = []
    for row in rows:
        try:
            value = row.get("Kp", row.get("kp_index")) if isinstance(row, dict) else row[1]
            values.append(float(value))
        except (ValueError, TypeError, KeyError, IndexError):
            continue
    if not values:
        raise RuntimeError("no Kp values parsed")
    last24 = values[-8:]  # 8 readings x 3 hours
    return {"max_kp": max(last24), "latest_kp": last24[-1], "samples": len(last24)}


def observe_quakes() -> dict:
    url = "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson"
    features = _get_json(url).get("features", [])
    mags = [
        f["properties"]["mag"]
        for f in features
        if isinstance(f.get("properties", {}).get("mag"), (int, float))
    ]
    if not mags:
        raise RuntimeError("no magnitudes in feed")
    strongest = max(features, key=lambda f: f["properties"].get("mag") or -99)
    return {
        "max_mag": round(max(mags), 2),
        "count": len(mags),
        "strongest_place": strongest["properties"].get("place"),
    }


def observe_wiki() -> dict:
    """The most-read English Wikipedia article for the last *complete* day."""
    day = datetime.now(timezone.utc) - timedelta(days=1)
    url = (
        "https://wikimedia.org/api/rest_v1/metrics/pageviews/top/"
        f"en.wikipedia/all-access/{day:%Y/%m/%d}"
    )
    articles = _get_json(url)["items"][0]["articles"]
    skip = {"Main_Page", "Special:Search", "-"}
    for art in articles:
        name = art.get("article", "")
        if name in skip or name.startswith("Special:"):
            continue
        return {
            "top": name,
            "views": art.get("views"),
            "for_date": f"{day:%Y-%m-%d}",
        }
    raise RuntimeError("no eligible article")


def observe_hn() -> dict:
    ids = _get_json("https://hacker-news.firebaseio.com/v0/topstories.json")[:10]
    if not ids:
        raise RuntimeError("empty top stories")
    title = None
    try:
        item = _get_json(f"https://hacker-news.firebaseio.com/v0/item/{ids[0]}.json")
        title = (item or {}).get("title")
    except Exception:
        pass  # the title is decoration; the id is what we actually grade on
    return {"top_id": ids[0], "top_title": title, "top10": ids}


def observe_weather() -> dict:
    """Daily highs for yesterday (settled) and tomorrow (forecast).

    `actual_prev` is a completed observation, which is what lets us grade a
    forecast honestly two days after it was made.
    """
    url = (
        "https://api.open-meteo.com/v1/forecast"
        f"?latitude={CITY_LAT}&longitude={CITY_LON}"
        "&daily=temperature_2m_max"
        f"&timezone={CITY_TZ.replace('/', '%2F')}"
        "&past_days=1&forecast_days=2"
    )
    daily = _get_json(url)["daily"]
    days, highs = daily["time"], daily["temperature_2m_max"]
    if len(days) < 3 or len(highs) < 3:
        raise RuntimeError("unexpected forecast shape")
    return {
        "city": CITY_NAME,
        "actual_prev": highs[0],
        "actual_prev_date": days[0],
        "today": highs[1],
        "forecast_next": highs[2],
        "forecast_next_date": days[2],
    }


OBSERVERS = {
    "btc": observe_btc,
    "kp": observe_kp,
    "quakes": observe_quakes,
    "wiki": observe_wiki,
    "hn": observe_hn,
    "weather": observe_weather,
}


# --------------------------------------------------------------------------
# archive access helpers
# --------------------------------------------------------------------------


def obs_of(days: dict, date: str, key: str):
    """Return day `date`'s observation `key`, or None if absent/failed."""
    day = days.get(date)
    if not isinstance(day, dict):
        return None
    value = (day.get("observations") or {}).get(key)
    if not isinstance(value, dict) or "error" in value:
        return None
    return value


def shift(date: str, delta: int) -> str:
    return (datetime.strptime(date, "%Y-%m-%d") + timedelta(days=delta)).strftime(
        "%Y-%m-%d"
    )


def _rate(days: dict, test, default: float, minimum: int = 5) -> float:
    """Historical frequency of `test` across archived days, for honest priors."""
    hits = [test(d) for d in days.values()]
    hits = [h for h in hits if h is not None]
    if len(hits) < minimum:
        return default
    return sum(hits) / len(hits)


# --------------------------------------------------------------------------
# predictors — make() calls tomorrow, resolve() reads the truth back out
# --------------------------------------------------------------------------
#
# make(obs, days, today) -> (call: bool, confidence: float, basis: dict) | None
#   confidence is always >= 0.5: it is confidence *in the call made*, not in
#   the event happening. A 0.7 "no" means 70% sure it will not happen.
#
# resolve(pred, days) -> bool | None
#   the actual outcome, or None if it cannot be settled yet (still open) or
#   the data needed to settle it never arrived (void).


def make_btc(obs, days, today, grades=()):
    btc = obs.get("btc")
    if not btc or btc.get("usd") is None:
        return None
    change = btc.get("usd_24h_change") or 0.0
    up = change >= 0
    # Momentum, held to a modest confidence — this is close to a coin flip and
    # pretending otherwise is how you get a bad calibration curve.
    conf = min(0.60, 0.52 + abs(change) / 100.0)
    return up, round(conf, 3), {"today_usd": btc["usd"], "change_24h": change}


def resolve_btc(pred, days):
    before = obs_of(days, pred["made_on"], "btc")
    after = obs_of(days, pred["resolve_on"], "btc")
    if not before or not after:
        return None
    if before.get("usd") is None or after.get("usd") is None:
        return None
    return after["usd"] > before["usd"]


def make_kp(obs, days, today, grades=()):
    kp = obs.get("kp")
    if not kp or kp.get("max_kp") is None:
        return None
    active = kp["max_kp"] > 3
    # Persistence: geomagnetic activity clusters, so today's state is the best
    # cheap guess at tomorrow's.
    return active, 0.70 if active else 0.78, {"today_max_kp": kp["max_kp"]}


def resolve_kp(pred, days):
    after = obs_of(days, pred["resolve_on"], "kp")
    if not after or after.get("max_kp") is None:
        return None
    return after["max_kp"] > 3


def make_quake(obs, days, today, grades=()):
    if not obs.get("quakes"):
        return None
    rate = _rate(
        days,
        lambda d: (
            (d.get("observations") or {}).get("quakes", {}).get("max_mag", 0) >= 5.0
            if isinstance((d.get("observations") or {}).get("quakes"), dict)
            else None
        ),
        default=0.85,
    )
    call = rate >= 0.5
    conf = rate if call else 1 - rate
    return call, round(min(0.95, max(0.5, conf)), 3), {"base_rate": round(rate, 3)}


def resolve_quake(pred, days):
    after = obs_of(days, pred["resolve_on"], "quakes")
    if not after or after.get("max_mag") is None:
        return None
    return after["max_mag"] >= 5.0


def make_wiki(obs, days, today, grades=()):
    wiki = obs.get("wiki")
    if not wiki or not wiki.get("top"):
        return None
    prev = obs_of(days, shift(today, -1), "wiki")
    streaking = bool(prev and prev.get("top") == wiki["top"])
    # An article that has already held the top spot two days running tends to
    # hold it again; a one-day spike usually does not.
    call = streaking
    return call, 0.70 if streaking else 0.62, {"today_top": wiki["top"]}


def resolve_wiki(pred, days):
    before = obs_of(days, pred["made_on"], "wiki")
    after = obs_of(days, pred["resolve_on"], "wiki")
    if not before or not after or not before.get("top") or not after.get("top"):
        return None
    return after["top"] == before["top"]


def make_hn(obs, days, today, grades=()):
    hn = obs.get("hn")
    if not hn or hn.get("top_id") is None:
        return None
    # The front page churns hard; falling out of the top 10 within a day is the
    # overwhelming default.
    return True, 0.88, {"top_id": hn["top_id"], "top_title": hn.get("top_title")}


def resolve_hn(pred, days):
    after = obs_of(days, pred["resolve_on"], "hn")
    if not after or not after.get("top10"):
        return None
    return pred["basis"]["top_id"] not in after["top10"]


def make_forecast(obs, days, today, grades=()):
    weather = obs.get("weather")
    if not weather or weather.get("forecast_next") is None:
        return None
    # We are not predicting the weather. We are predicting whether the weather
    # service gets it right — and quietly building a scorecard on them.
    return (
        True,
        0.80,
        {
            "forecast_c": weather["forecast_next"],
            "for_date": weather.get("forecast_next_date"),
            "city": weather.get("city"),
        },
    )


def resolve_forecast(pred, days):
    """Settled by whichever later run carried the completed high for that date."""
    target = pred["basis"].get("for_date") or pred["resolve_on"]
    forecast = pred["basis"].get("forecast_c")
    if forecast is None:
        return None
    for date in sorted(days):
        if date <= pred["made_on"]:
            continue
        weather = obs_of(days, date, "weather")
        if not weather:
            continue
        if weather.get("actual_prev_date") == target and weather.get("actual_prev") is not None:
            return abs(weather["actual_prev"] - forecast) <= FORECAST_TOLERANCE_C
    return None


PREDICTORS = {
    "btc_up": {
        "question": "Bitcoin will be higher tomorrow than it is today.",
        "rule": "momentum",
        "horizon": 1,
        "make": make_btc,
        "resolve": resolve_btc,
    },
    "kp_storm": {
        "question": "Geomagnetic Kp will exceed 3 within the next 24 hours.",
        "rule": "persistence",
        "horizon": 1,
        "make": make_kp,
        "resolve": resolve_kp,
    },
    "quake_m5": {
        "question": "A magnitude 5.0+ earthquake will strike somewhere tomorrow.",
        "rule": "base rate",
        "horizon": 1,
        "make": make_quake,
        "resolve": resolve_quake,
    },
    "wiki_hold": {
        "question": "Today's most-read Wikipedia article will still be #1 tomorrow.",
        "rule": "persistence",
        "horizon": 1,
        "make": make_wiki,
        "resolve": resolve_wiki,
    },
    "hn_fade": {
        "question": "The current #1 story on Hacker News will fall out of the top 10.",
        "rule": "decay",
        "horizon": 1,
        "make": make_hn,
        "resolve": resolve_hn,
    },
    "forecast_hit": {
        "question": (
            f"Tomorrow's high in {CITY_NAME} will land within "
            f"{FORECAST_TOLERANCE_C:g}°C of today's forecast."
        ),
        "rule": "trust the forecaster",
        "horizon": 2,  # needs a *completed* day, so it settles a day later
        "make": make_forecast,
        "resolve": resolve_forecast,
    },
}

# Every rule above is the "rule" variant of its own family.
for _family, _spec in PREDICTORS.items():
    _spec["family"] = _family
    _spec["variant"] = "rule"


def _ml(family: str):
    """Build the model variant of a family: same question, learned answer.

    It borrows the rule's `basis` so the shared resolver settles both variants
    identically — the two are answering the exact same question, and the only
    thing that differs is how the call was reached.
    """

    def make(obs, days, today, grades=()):
        import learn  # lazy: learn imports predict, so not at module load

        base = PREDICTORS[family]["make"](obs, days, today)
        if base is None:
            return None  # no data today; the rule sat this one out too
        _, _, basis = base

        result = learn.probability(family, days, grades, today)
        if result is None:
            return None  # not enough settled history to train on yet
        p_event, detail = result
        call, confidence = learn.call_and_confidence(p_event)

        basis = dict(basis)
        basis["model"] = {"p_event": round(p_event, 4), **detail}
        return call, confidence, basis

    return make


# Each family runs twice a day: once by rule, once by model, on the same
# question and settled by the same resolver. The rule is the control — without
# it there is no way to show whether the model is earning its complexity.
for _family, _spec in list(PREDICTORS.items()):
    PREDICTORS[f"{_family}_ml"] = {
        "question": _spec["question"],
        "rule": "logistic regression",
        "horizon": _spec["horizon"],
        "family": _family,
        "variant": "model",
        "make": _ml(_family),
        "resolve": _spec["resolve"],
    }


# --------------------------------------------------------------------------
# the three phases
# --------------------------------------------------------------------------


def collect_observations() -> dict:
    out = {}
    for name, fn in OBSERVERS.items():
        try:
            out[name] = fn()
            print(f"[ok]   observe {name}")
        except Exception as err:
            out[name] = {"error": str(err)}
            print(f"[fail] observe {name}: {err}")
    return out


def make_predictions(obs: dict, days: dict, today: str, grades=()) -> list:
    """Place today's bets.

    `grades` is the settled record so far — the model variants train on it.
    It never contains anything resolving today or later, which is what keeps
    the models walk-forward.
    """
    preds = []
    for pid, spec in PREDICTORS.items():
        try:
            result = spec["make"](obs, days, today, grades)
        except Exception as err:
            print(f"[fail] predict {pid}: {err}")
            continue
        if result is None:
            print(f"[skip] predict {pid}: no data")
            continue
        call, confidence, basis = result
        preds.append(
            {
                "id": pid,
                "question": spec["question"],
                "rule": spec["rule"],
                "family": spec["family"],
                "variant": spec["variant"],
                "call": bool(call),
                "confidence": float(confidence),
                "basis": basis,
                "made_on": today,
                "resolve_on": shift(today, spec["horizon"]),
            }
        )
        print(f"[ok]   predict {pid}: {call} @ {confidence}")
    return preds


def grade_all(days: dict) -> list:
    """Re-derive every settled prediction from the archive. Pure and idempotent.

    Anything that cannot be settled is simply absent — still open, or void
    because the day that would have settled it never got archived.
    """
    grades = []
    for date in sorted(days):
        for pred in days[date].get("predictions") or []:
            spec = PREDICTORS.get(pred.get("id"))
            if not spec:
                continue
            try:
                actual = spec["resolve"](pred, days)
            except Exception:
                actual = None
            if actual is None:
                continue
            grades.append(
                {
                    "id": pred["id"],
                    "question": pred.get("question"),
                    "rule": pred.get("rule"),
                    "family": spec["family"],
                    "variant": spec["variant"],
                    "made_on": pred["made_on"],
                    "resolve_on": pred["resolve_on"],
                    "call": pred["call"],
                    "confidence": pred["confidence"],
                    "actual": actual,
                    "correct": pred["call"] == actual,
                }
            )
    return grades


# --------------------------------------------------------------------------
# the ledger
# --------------------------------------------------------------------------

BUCKETS = ((0.5, 0.6), (0.6, 0.7), (0.7, 0.8), (0.8, 0.9), (0.9, 1.001))

# Log loss is unbounded: a confident, wrong call at p=0 costs infinity and would
# poison the average forever. Clamping is the standard treatment, and the models
# are capped at 95% anyway — this only ever bites a hand-written rule.
LOG_LOSS_EPS = 1e-15

# What saying "fifty-fifty" to everything scores, on any set of bets whatsoever.
# These are constants, not measurements, which is exactly why they are the
# reference: a Brier above 0.25 means the predictor is worse than shrugging.
COIN_FLIP_BRIER = 0.25
COIN_FLIP_LOG_LOSS = round(math.log(2), 4)


def p_event(grade: dict) -> float:
    """The probability a prediction assigned to the event actually happening.

    Confidence is always stated in the *call*, not the event — a 70% "no" is a
    30% chance of the event — so every scoring rule has to convert first.
    """
    return grade["confidence"] if grade["call"] else 1.0 - grade["confidence"]


def score(grades: list) -> dict:
    """Accuracy, Brier and log loss over one set of settled bets.

    Every figure carries its own `n`. A 0.09 Brier over four bets and one over
    four hundred are not the same claim, and a table printing only the number
    invites the reader to assume the second.

    Brier is the mean squared error of the probability assigned to the event:
    0 is perfect, 0.25 is what "50% to everything" earns, above that is worse
    than useless. Log loss punishes confident mistakes far harder than Brier
    does, which is the point of reporting both — accuracy alone cannot tell a
    cautious miss from a reckless one.
    """
    n = len(grades)
    if not n:
        return {"n": 0, "correct": 0, "accuracy": None, "brier": None, "log_loss": None}

    correct = sum(1 for g in grades if g["correct"])
    brier_total = 0.0
    log_loss_total = 0.0
    for g in grades:
        p = p_event(g)
        truth = 1.0 if g["actual"] else 0.0
        brier_total += (p - truth) ** 2
        clamped = min(1.0 - LOG_LOSS_EPS, max(LOG_LOSS_EPS, p))
        log_loss_total += -(truth * math.log(clamped) + (1 - truth) * math.log(1 - clamped))

    return {
        "n": n,
        "correct": correct,
        "accuracy": round(correct / n, 4),
        "brier": round(brier_total / n, 4),
        "log_loss": round(log_loss_total / n, 4),
    }


def coin_flip(n: int) -> dict:
    """The 50%-to-everything baseline, over `n` bets.

    Carried in the ledger rather than left for the reader to remember, so every
    real score sits next to the number it has to beat to have meant anything.
    """
    if not n:
        return {"n": 0, "accuracy": None, "brier": None, "log_loss": None}
    return {
        "n": n,
        "accuracy": 0.5,
        "brier": COIN_FLIP_BRIER,
        "log_loss": COIN_FLIP_LOG_LOSS,
    }


def base_rate(grades: list) -> dict:
    """How often the event actually happened, and what always calling the
    majority side would have scored.

    This is the figure that says whether a question is *predictable* at all.
    `quake_m5` fires on roughly 85% of days, so a rule that scores 85% accuracy
    has demonstrated nothing — it has matched a constant. Without this column a
    reader cannot tell that apart from real skill.
    """
    n = len(grades)
    if not n:
        return {"n": 0, "rate": None, "majority_accuracy": None}
    happened = sum(1 for g in grades if g["actual"])
    rate = happened / n
    return {
        "n": n,
        "rate": round(rate, 4),
        "majority_accuracy": round(max(rate, 1.0 - rate), 4),
    }


def build_ledger(days: dict, grades: list, today: str) -> dict:
    overall = score(grades)
    graded = overall["n"]
    correct = overall["correct"]
    brier = overall["brier"]

    by_predictor = {}
    for pid, spec in PREDICTORS.items():
        mine = [g for g in grades if g["id"] == pid]
        marks = score(mine)
        by_predictor[pid] = {
            "question": spec["question"],
            "rule": spec["rule"],
            "family": spec["family"],
            "variant": spec["variant"],
            "graded": marks["n"],
            "correct": marks["correct"],
            "accuracy": marks["accuracy"],
            "brier": marks["brier"],
            "log_loss": marks["log_loss"],
        }

    calibration = []
    for low, high in BUCKETS:
        mine = [g for g in grades if low <= g["confidence"] < high]
        if not mine:
            calibration.append(
                {"label": f"{int(low*100)}–{int(high*100)}%", "n": 0,
                 "claimed": None, "actual": None}
            )
            continue
        calibration.append(
            {
                "label": f"{int(low*100)}–{int(high*100)}%",
                "n": len(mine),
                "claimed": round(sum(g["confidence"] for g in mine) / len(mine), 4),
                "actual": round(sum(1 for g in mine if g["correct"]) / len(mine), 4),
            }
        )

    settled = {(g["made_on"], g["id"]) for g in grades}
    open_bets, void = [], 0
    for date in sorted(days):
        for pred in days[date].get("predictions") or []:
            if (pred["made_on"], pred["id"]) in settled:
                continue
            if pred["resolve_on"] > today:
                open_bets.append(pred)
            else:
                void += 1

    return {
        "updated": datetime.now(timezone.utc).isoformat(),
        "head_to_head": build_head_to_head(grades),
        "totals": {
            "graded": graded,
            "correct": correct,
            "accuracy": overall["accuracy"],
            "brier": brier,
            "log_loss": overall["log_loss"],
            "open": len(open_bets),
            "void": void,
            "days": len(days),
        },
        # The numbers every figure above has to beat before it means anything.
        "baselines": {
            "coin_flip": coin_flip(graded),
            "base_rate": base_rate(grades),
        },
        "by_predictor": by_predictor,
        "calibration": calibration,
        "open_bets": open_bets,
        "grades": grades,
    }


def build_head_to_head(grades: list) -> dict:
    """Rule versus model, per family, on **shared days only**.

    The model cannot bet until it has 25 settled examples, so it will always
    have fewer bets than the rule. Comparing their lifetime accuracies would
    quietly compare different sets of days and flatter whichever got the easier
    ones. Only days where both placed a bet count here.
    """
    paired: dict = {}
    everything: dict = {}
    for grade in grades:
        family = grade.get("family")
        variant = grade.get("variant")
        if not family or not variant:
            continue  # a prediction archived before variants existed
        paired.setdefault(family, {}).setdefault(grade["made_on"], {})[variant] = grade
        everything.setdefault(family, []).append(grade)

    out = {}
    for family, dates in paired.items():
        both = [p for p in dates.values() if "rule" in p and "model" in p]
        # Scored on the same shared days, which is the fairer comparison:
        # accuracy alone ignores how confidently each one was wrong.
        rule = score([p["rule"] for p in both])
        model = score([p["model"] for p in both])

        out[family] = {
            "question": PREDICTORS[family]["question"],
            "shared_days": len(both),
            "rule_correct": rule["correct"],
            "model_correct": model["correct"],
            "rule_accuracy": rule["accuracy"],
            "model_accuracy": model["accuracy"],
            "rule_brier": rule["brier"],
            "model_brier": model["brier"],
            "rule_log_loss": rule["log_loss"],
            "model_log_loss": model["log_loss"],
            # Both references travel with the row. Coin flip is what beating
            # nothing looks like; base rate is measured over the family's whole
            # settled record, so it is populated long before the model is warm
            # enough to appear in the shared-day columns at all.
            "coin_flip": coin_flip(len(both)),
            "base_rate": base_rate(everything.get(family, [])),
        }
    return out


def build_index(days: dict, grades: list) -> list:
    """One entry per archived day, for the hit/miss calendar."""
    entries = []
    for date in sorted(days):
        day = days[date]
        captured = [
            name
            for name in OBSERVERS
            if isinstance((day.get("observations") or {}).get(name), dict)
            and "error" not in day["observations"][name]
        ]
        mine = [g for g in grades if g["made_on"] == date]
        entries.append(
            {
                "date": date,
                "captured": captured,
                "made": len(day.get("predictions") or []),
                "graded": len(mine),
                "correct": sum(1 for g in mine if g["correct"]),
            }
        )
    return entries


# --------------------------------------------------------------------------
# writing
# --------------------------------------------------------------------------


def load_days() -> dict:
    days = {}
    if not ARCHIVE.exists():
        return days
    for path in sorted(ARCHIVE.glob("*.json")):
        if path.stem in ("latest", "index", "ledger"):
            continue
        try:
            day = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            continue
        if isinstance(day, dict) and day.get("date"):
            days[day["date"]] = day
    return days


def _write(path: Path, payload) -> None:
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    try:
        shown = path.relative_to(ROOT)
    except ValueError:  # writing outside the repo (tests, backfills)
        shown = path
    print(f"wrote {shown}")


def update_readme(snapshot: dict, ledger: dict) -> None:
    if not README.exists():
        return
    totals = ledger["totals"]
    baselines = ledger.get("baselines") or {}
    coin = baselines.get("coin_flip") or {}

    def num(value, places=3):
        return "—" if value is None else f"{value:.{places}f}"

    lines = [
        "<!-- LEDGER:START -->",
        f"### Standing — {snapshot['date']}",
        "",
    ]
    if totals["graded"]:
        lines += [
            f"**{totals['correct']} right / {totals['graded']} settled "
            f"({totals['accuracy']:.0%})** · Brier {num(totals['brier'])} "
            f"· log loss {num(totals['log_loss'])} · {totals['open']} still open",
            "",
            f"Saying \"50%\" to all {totals['graded']} of them instead would score "
            f"Brier {num(coin.get('brier'))}, log loss {num(coin.get('log_loss'))}. "
            "Lower is better; every figure below is only worth what it beats.",
            "",
            "| Call | Answered by | Settled | Right | Brier | Log loss |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        # The model variants sit out until they have 25 settled examples in
        # their family. Printing a dozen empty rows until then buries the six
        # that actually have a record, so they appear only once they do.
        for row in ledger["by_predictor"].values():
            if row["variant"] == "model" and not row["graded"]:
                continue
            right = (
                f"{row['correct']}/{row['graded']} ({row['accuracy']:.0%})"
                if row["graded"]
                else "—"
            )
            lines.append(
                f"| {row['question']} | {row['rule']} | n={row['graded']} | {right} "
                f"| {num(row['brier'])} | {num(row['log_loss'])} |"
            )
        lines.append(
            f"| _coin flip — the baseline_ | _50% to everything_ | n={totals['graded']} "
            f"| _50%_ | _{num(coin.get('brier'))}_ | _{num(coin.get('log_loss'))}_ |"
        )
        lines.append("")
        lines.append(
            f"_Sample is {totals['graded']} settled bets across {totals['days']} "
            "days. Nothing here is significant yet, and it is published daily "
            "precisely so that it becomes so._"
        )
        lines.append("")
    else:
        lines += ["_No bets have settled yet — the first ones resolve tomorrow._", ""]

    if snapshot.get("predictions"):
        lines += ["**Open bets, placed today:**", ""]
        for pred in snapshot["predictions"]:
            verdict = "**yes**" if pred["call"] else "**no**"
            lines.append(
                f"- {verdict} — {pred['question']} "
                f"_({pred['confidence']:.0%} confident, {pred['rule']})_"
            )
        lines.append("")
    lines.append("<!-- LEDGER:END -->")
    block = "\n".join(lines)

    text = README.read_text(encoding="utf-8")
    start, end = "<!-- LEDGER:START -->", "<!-- LEDGER:END -->"
    if start in text and end in text:
        text = text[: text.index(start)] + block + text[text.index(end) + len(end) :]
    else:
        text = text.rstrip() + "\n\n" + block + "\n"
    README.write_text(text, encoding="utf-8")
    print("wrote README.md")


def main() -> None:
    now = datetime.now(timezone.utc)
    today = now.strftime("%Y-%m-%d")
    ARCHIVE.mkdir(exist_ok=True)

    days = load_days()

    print("-- observe --")
    observations = collect_observations()

    # Today's observations are the truth that settles yesterday's bets, so
    # grading happens *before* predicting. That ordering is what makes the
    # models walk-forward: they train on this settled record, which by
    # construction contains nothing that resolves today or later.
    print("-- grade --")
    days[today] = {"date": today, "observations": observations, "predictions": []}
    grades = grade_all(days)

    print("-- predict --")
    predictions = make_predictions(observations, days, today, grades)

    snapshot = {
        "date": today,
        "fetched_at": now.isoformat(),
        "observations": observations,
        "predictions": predictions,
    }
    _write(ARCHIVE / f"{today}.json", snapshot)
    days[today] = snapshot

    # Recomputed over the finished archive; today's fresh bets cannot settle
    # yet, so this matches the grading above and stays a pure function of it.
    grades = grade_all(days)
    ledger = build_ledger(days, grades, today)
    totals = ledger["totals"]
    print(
        f"settled {totals['graded']} · correct {totals['correct']} "
        f"· open {totals['open']} · void {totals['void']}"
    )

    _write(ARCHIVE / "latest.json", snapshot)
    _write(ARCHIVE / "ledger.json", ledger)
    _write(ARCHIVE / "index.json", build_index(days, grades))
    update_readme(snapshot, ledger)
    print("done")


if __name__ == "__main__":
    main()
